server:
  port: 9001
spring:
  application:
    name: spring-cloud-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  hystrix:
    enabled: true
